include(mcp9808.m4)
define(AP, "changeme")
define(AP_PASS, "changeme")
define(FLASH_FAST_MS, 120)
define(FLASH_SLOW_MS, 800)
define(I2C_SCL, 5)
define(I2C_SDA, 6)
define(IDLE_MS, 5000)
define(LED_BAD, 1)
define(LED_GOOD, 2)
define(LED_IDLE, 3)
define(LED_TX, 4)
define(MQTT_IP, "changeme")
define(MQTT_NAME, "changeme")
define(MQTT_TIMEOUT, 120)
define(MQTT_TOPIC, "changeme/" .. MQTT_NAME)
